/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    fontSize: {
      xs: "11px",
      sm: "12px",
      base: "14px",
      lg: "16px",
      xl: "18px",
      "2xl": "20px",
      "3xl": "24px",
      "4xl": "30px",
      "5xl": "36px",
    },
    extend: {
      colors: {
        spectrum: {
          gray: {
            50: "#ffffff",
            75: "#fafafa",
            100: "#f5f5f5",
            200: "#eaeaea",
            300: "#e1e1e1",
            400: "#cacaca",
            500: "#b3b3b3",
            600: "#8e8e8e",
            700: "#6e6e6e",
            800: "#4b4b4b",
            900: "#2c2c2c",
          },
          blue: {
            400: "#2680eb",
            500: "#1473e6",
            600: "#0d66d0",
          },
        },
      },
    },
  },
  corePlugins: {
    preflight: false,
    transform: false,
    transformOrigin: false,
    scale: false,
    rotate: false,
    translate: false,
    skew: false,
    transitionProperty: false,
    transitionDuration: false,
    transitionTimingFunction: false,
    transitionDelay: false,
    animation: false,
    boxShadow: false,
    textShadow: false,
    gradientColorStops: false,
    backgroundImage: false,
    backgroundClip: false,
    gap: false,
    gridAutoColumns: false,
    gridAutoFlow: false,
    gridAutoRows: false,
    gridColumn: false,
    gridColumnEnd: false,
    gridColumnStart: false,
    gridRow: false,
    gridRowEnd: false,
    gridRowStart: false,
    gridTemplateColumns: false,
    gridTemplateRows: false,
    position: false,
    inset: false,
    zIndex: false,
    blur: false,
    brightness: false,
    contrast: false,
    dropShadow: false,
    grayscale: false,
    hueRotate: false,
    invert: false,
    saturate: false,
    sepia: false,
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    mixBlendMode: false,
    backgroundBlendMode: false,
  },
  plugins: [],
};
